image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login registry.ikt.im -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker build -t registry.ikt.im/$CI_PROJECT_PATH:latest .
    - docker push registry.ikt.im/$CI_PROJECT_PATH:latest
  only:
    - master

