name: Docker

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  REGISTRY: registry.ikt.im
  IMAGE_NAME: sampsharp.net

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        if: github.ref == 'refs/heads/master'
        uses: actions/checkout@v2

      - name: Log into registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1.9.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
